version: '2.2'

services:
  openhab:
    build: .
#      context: .
#      dockerfile: Dockerfile
#    image: "openhab/openhab:3.2.0"
    restart: always
    network_mode: host
    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
      - "/home/juergen/dev/docker/volumes/openhab/openhab_addons:/openhab/addons"
      - "/home/juergen/dev/docker/volumes/openhab/openhab_conf:/openhab/conf"
      - "/home/juergen/dev/docker/volumes/openhab/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"

volumes:
  openhab_addons:
    driver: local
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local
