version: '2.0'
#
# look at: https://docs.docker.com/compose/wordpress/
#
services:
   db:
     container_name: wp-database-test
     image: mysql:5.7
     volumes:
       - wp-database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     container_name: wordpress-test
     depends_on:
       - db
     image: wordpress:4.9.1-php7.0-apache
     volumes:
           - wp-files:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    wp-database:
    wp-files:
    
